/* Generated from protocol/adas_can_v3.yaml. */
/* Do not edit by hand; run tools/generate_protocol.py. */
#ifndef ADAS_CAN_PROTOCOL_V3_GENERATED_H_
#define ADAS_CAN_PROTOCOL_V3_GENERATED_H_

#define ADAS_PROTOCOL_VERSION_V3 3U
#define ADAS_CAN_BITRATE_BPS 500000UL
#define CANID_PRIMARY_HEARTBEAT 0x100U
#define CANID_PRIMARY_LATERAL 0x101U
#define CANID_PRIMARY_LONGITUDINAL 0x102U
#define CANID_PRIMARY_STATUS 0x103U
#define CANID_PRIMARY_SESSION_CONTROL 0x104U
#define CANID_BACKUP_HEARTBEAT 0x110U
#define CANID_BACKUP_LATERAL 0x111U
#define CANID_BACKUP_LONGITUDINAL 0x112U
#define CANID_BACKUP_STATUS 0x113U
#define CANID_BACKUP_SESSION_CONTROL 0x114U
#define CANID_MCU_CONTROL 0x201U
#define CANID_MCU_HEARTBEAT 0x202U
#define CANID_MCU_DIAG 0x203U
#define CANID_MCU_E2E_DIAG 0x204U
#define CANID_MCU_LINK_STATS 0x205U
#define CANID_MCU_SESSION_STATUS 0x206U
#define CANID_FAULT_INJECT 0x301U
#define CANID_FAULT_RESPONSE 0x302U

#define HIL_REQ_NONE 0U
#define HIL_REQ_ANNOUNCE 1U
#define HIL_REQ_SYNC_STANDBY 2U
#define HIL_REQ_PREPARE_ARM 3U
#define HIL_REQ_COMMIT_ACTIVE 4U
#define HIL_REQ_ACTIVE 5U
#define HIL_REQ_REARM 6U
#define HIL_REQ_ABORT 7U

#define HIL_ACK_BOOT_WAIT 0U
#define HIL_ACK_SESSION_ACCEPTED 1U
#define HIL_ACK_READY 2U
#define HIL_ACK_ARMED 3U
#define HIL_ACK_ACTIVE 4U
#define HIL_ACK_RECOVERY_REQUIRED 5U
#define HIL_ACK_REJECTED 6U
#define HIL_ACK_FAULT_LOCK 7U

#define HIL_REJECT_NONE 0U
#define HIL_REJECT_PROTOCOL_MISMATCH 1U
#define HIL_REJECT_SESSION_MISMATCH 2U
#define HIL_REJECT_FRAMES_NOT_FRESH 3U
#define HIL_REJECT_UNSAFE_TO_ARM 4U
#define HIL_REJECT_OPERATOR_AUTHORIZATION_REQUIRED 5U
#define HIL_REJECT_FAULT_NOT_RECOVERABLE 6U
#define HIL_REJECT_INVALID_TRANSITION 7U
#define HIL_REJECT_INVALID_SEQUENCE 8U

#define HIL_SESSION_B_VERSION 0U
#define HIL_SESSION_B_PHASE 1U
#define HIL_SESSION_B_ID 2U
#define HIL_SESSION_B_SEQUENCE 6U
#define HIL_SESSION_B_CRC 7U

#endif /* ADAS_CAN_PROTOCOL_V3_GENERATED_H_ */
